// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQa_e_4t123OOi3jI9u9DyDjXkWaiOuQE',
    appId: '1:1751102600:web:5197a1b8799dc7f8601b3d',
    messagingSenderId: '1751102600',
    projectId: 'basicproject-71450',
    authDomain: 'basicproject-71450.firebaseapp.com',
    storageBucket: 'basicproject-71450.appspot.com',
    measurementId: 'G-LGLKVBGN23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgwsukze0ZmPPqoClux5L2KPhPioZFpvc',
    appId: '1:1751102600:android:272463d12af91d7f601b3d',
    messagingSenderId: '1751102600',
    projectId: 'basicproject-71450',
    storageBucket: 'basicproject-71450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXaRm83z3DtfYkw_Q6Pz1J8I965Df7sUw',
    appId: '1:1751102600:ios:b091af0d1e1b16ce601b3d',
    messagingSenderId: '1751102600',
    projectId: 'basicproject-71450',
    storageBucket: 'basicproject-71450.appspot.com',
    iosBundleId: 'com.example.basicfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXaRm83z3DtfYkw_Q6Pz1J8I965Df7sUw',
    appId: '1:1751102600:ios:b091af0d1e1b16ce601b3d',
    messagingSenderId: '1751102600',
    projectId: 'basicproject-71450',
    storageBucket: 'basicproject-71450.appspot.com',
    iosBundleId: 'com.example.basicfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQa_e_4t123OOi3jI9u9DyDjXkWaiOuQE',
    appId: '1:1751102600:web:8534b354f768c0c4601b3d',
    messagingSenderId: '1751102600',
    projectId: 'basicproject-71450',
    authDomain: 'basicproject-71450.firebaseapp.com',
    storageBucket: 'basicproject-71450.appspot.com',
    measurementId: 'G-GRREVW9EPQ',
  );
}
